### ISSUE TITLE
Media for FB and TW

### ISSUE THREAD

**Issue by vlafiser** [olahol/react-social#1]
Hi man,

thank you for this component! But, how works the Media for FB and TW?

If I'm trying something like this:

```javascript
var media = "http://someUrl.com/imageName.png";
...
<FacebookButton url={url} media={media}>
    FB share
</FacebookButton>
```

nothing happen there. Can you help me, how include the image there? Thank you!

V.

**Comment by olahol** [comment]
Sadly Facebook does not allow custom inputs to their `sharer.php` anymore. I have added a `message` prop though to the Facebook and Twitter buttons though, that can be used to add an image that Twitter/Facebook might pick up.
