### ISSUE TITLE
Shouldn't the app_id for Facebook be settable?

### ISSUE THREAD

**Issue by queso** [olahol/react-social#14]
It seems the app_id is hardcoded: https://github.com/olahol/react-social/blob/f4fd7c30fccab6e3e497cb97b8b481b9e52581a4/react-social.js#L249.

From what I've read, this should be set per app, not hardcoded.

**Comment by olahol** [comment]
You are completely right @queso, I am going to do an overhaul of the library in the near future to fix this and other things, thank you for bringing this to my attention.

**Comment by queso** [comment]
Happy to help with a PR as I need to get it fixed today for a production deploy this week :)

**Comment by olahol** [comment]
Thank you, it's up as version `1.0.6`, I changed `app_id` to `appId` to make it more consistent with the other interfaces, good luck with the production deploy :smile:
