### ISSUE TITLE
Problem with server rendering

### ISSUE THREAD

**Issue by efernandesng** [olahol/react-social#19]
`warning.js:45 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`

```
warning @ warning.js:45
getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:34
ReactUpdateQueue.enqueueSetState  @ ReactUpdateQueue.js:181
ReactComponent.setState @ ReactComponent.js:65
(anonymous function) @ react-social.js:143
(anonymous function) @ ?callback=jsonp_1463407624090_466&url=http%3A%2F%2F127.0.0.1%3A3000%2Fpagina%2Fcronologia-dos-acont…:1
```

react@0.14.8

**Comment by olahol** [comment]
In version `1.2.0` I've moved updating count to componentDidMount, see if this helps.

**Comment by efernandesng** [comment]
Thanks for update :)

Apparently the problem is fixed, but occurs another similar problem: when the component make jsonp request and is unmounted before it finish we get another getState warning. A possible solution is cancel all pending requests in `componentWillUnmount`.
