### ISSUE TITLE
window.open(url, target)

### ISSUE THREAD

**Issue by jetarin-min** [olahol/react-social#20]
Hi,
Is it possible to pass a prop target to define target type. I want pop up instead of new window.
I saw on the code here
` 
        if (typeof result === "object") {
          var url = result[0]
          var target = result[1]
        } else {
          var url = result
          var target = "_blank"
        }
        window.open(url, target);
`
Thanks

**Comment by olahol** [comment]
In version `1.2.0` I've added a `target` prop, try it out and see if that's what you want :+1:
