### ISSUE TITLE
Pocket

### ISSUE THREAD

**Issue by slorber** [olahol/react-social#28]
Hi,

It seems it's possible to share to pocket and have a count.
I've also seen donreach supports a count for pocket.

https://getpocket.com/publisher/button

It would be nice to support Pocket as well

**Comment by olahol** [comment]
Yep, I will look to add this today.

**Comment by slorber** [comment]
great thanks :)

**Comment by olahol** [comment]
I've added `PocketButton` and `PocketCount` (using donreach API) in version `1.4.0`.

**Comment by slorber** [comment]
that was fast thanks :)
