### ISSUE TITLE
TwitterButton fails on iOS

### ISSUE THREAD

**Issue by eriklharper** [olahol/react-social#3]
Hi, just tried using the TwitterButton component and it works fine on desktop browsers, however I see that on a iPhone it directs to a mobile.twitter.com side with the embedded message in the URL, but all I see on the phone is the Twitter Home page with the list of Tweets on the account.  No compose tweet UI pops up like on Desktop.

Is this a known issue?

**Comment by olahol** [comment]
Sorry for not getting back to you sooner, I was able to fix this issue by updating the Twitter sharing endpoint.

**Comment by eriklharper** [comment]
Thanks @olahol I'll check it out :)
