### ISSUE TITLE
Truncate Twitter text automatically?

### ISSUE THREAD

**Issue by slorber** [olahol/react-social#30]
Hi,

```
var msg = this.props.message === "" ?
        this.props.url : this.props.message + " " + this.props.url;
```

The url is shortened by twitter automatically and the size is always 23, so it makes sense to automatically truncate the message with a limit of (140 - 24) I think

**Comment by olahol** [comment]
Maybe, there is an argument for leaving it as it is as Twitter has made noises about abandoning the 140 character limit in the future, also overriding user input might surprise some people and lead to debugging headaches for them.

**Comment by slorber** [comment]
that's true, I'll implement this on my side
