### ISSUE TITLE
facebook share button requires app id?

### ISSUE THREAD

**Issue by riverKanies** [olahol/react-social#35]
I chose to use this package because when I originally went through the example and implemented it, it just worked (for facebook and twitter). Now however, it is acting like it expects and facebook app id. Does this require an app id? If so, why no mention in example. If not, why am I getting the error? 
- when I click the fb button it renders a fb error: Invalid App ID: 0
- url: https://www.facebook.com/dialog/feed?app_id=undefined&display=popup&caption=&link=http%3A%2F%2Flocalhost%3A3000%2Fcommunities%2F1%2Fposts%2F231&redirect_uri=https%3A%2F%2Fwww.facebook.com%2F

**Comment by arvinkx** [comment]
As far as I can tell, this is new on FB's end - it looks like they want an app ID now. Even FB's button builder asks for one. The FB button will need to be amended to require an app ID.

**Comment by riverKanies** [comment]
well that sucks... but I'm excited that I brought up a legitimate github issue! (it's my first)

**Comment by riverKanies** [comment]
I may push up a PR for the fix if that would be helpful

**Comment by arvinkx** [comment]
That would be fantastic!

**Comment by riverKanies** [comment]
wait, there's already an appId prop...

**Comment by olahol** [comment]
@riverKanies you are completely right that the `appId` should be required.

**Comment by riverKanies** [comment]
@olahol opened a pr! hooray for open source! would love to have you merge it. also, will totally make any changes you suggest

**Comment by olahol** [comment]
Hooray!
