### ISSUE TITLE
Implement prop isPopup ?

### ISSUE THREAD

**Issue by thanhtungdp** [olahol/react-social#37]
React-social is a good package.
I think you should implement prop isPopup, and if isPopup == true, then open new popup window instead open new tab. 
Example: http://www.rapidtables.com/web/html/link/html-link-new-window.htm

**Comment by eminx** [comment]
I think the `sharer` prop already triggers `display=popup` but for some reason it gets canceled along the way. I can not address if it's due to facebook or the plugin though...

But you're right, it should be optional.

**Comment by savovs** [comment]
This would be awesome! Currently it opens up a new tab by default.

**Comment by olahol** [comment]
I've merged https://github.com/olahol/react-social/pull/46 , which implements this for `FacebookButton`.
