### ISSUE TITLE
React.renderToString error: react-social uses jsonp and requires a browser environment

### ISSUE THREAD

**Issue by gbuszmicz** [olahol/react-social#4]
Hi, how are you.
I´m having some trouble using this component with React.renderToString. 
I get this error:

```
error: uncaughtException: react-social uses jsonp and requires a browser environment
```

from this line i guess:
```
[...]
  if (typeof document === "undefined" || typeof window === "undefined") {
    throw new Error("react-social uses jsonp and requires a browser environment");
  }
[...]
```

Is there a way to get this working?
Thanks!

**Comment by olahol** [comment]
Sorry for not getting back to you sooner, I have updated `react-social` with the possibility of rendering to string, check out version `0.1.7` on NPM.

**Comment by gbuszmicz** [comment]
Thank you @olahol, I will check it out!!
