### ISSUE TITLE
Remove React warnings for PropTypes and createClass

### ISSUE THREAD

**Issue by pcmaffey** [olahol/react-social#57]
> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

> Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

**Comment by knynkwl** [comment]
+1

**Comment by olahol** [comment]
Version `1.10.0` now uses `prop-types` and `create-react-class`.
